export interface BibleBookInfo {
  name: string;
  slug: string;
  testament: 'AT' | 'NT';
  category: string;
  chapters: number;
}

export const BIBLE_BOOKS: BibleBookInfo[] = [
  // Antigo Testamento (39 livros)
  { name: 'Gênesis', slug: 'genesis', testament: 'AT', category: 'Pentateuco', chapters: 50 },
  { name: 'Êxodo', slug: 'exodus', testament: 'AT', category: 'Pentateuco', chapters: 40 },
  { name: 'Levítico', slug: 'leviticus', testament: 'AT', category: 'Pentateuco', chapters: 27 },
  { name: 'Números', slug: 'numbers', testament: 'AT', category: 'Pentateuco', chapters: 36 },
  { name: 'Deuteronômio', slug: 'deuteronomy', testament: 'AT', category: 'Pentateuco', chapters: 34 },
  { name: 'Josué', slug: 'joshua', testament: 'AT', category: 'Históricos', chapters: 24 },
  { name: 'Juízes', slug: 'judges', testament: 'AT', category: 'Históricos', chapters: 21 },
  { name: 'Rute', slug: 'ruth', testament: 'AT', category: 'Históricos', chapters: 4 },
  { name: '1 Samuel', slug: '1+samuel', testament: 'AT', category: 'Históricos', chapters: 31 },
  { name: '2 Samuel', slug: '2+samuel', testament: 'AT', category: 'Históricos', chapters: 24 },
  { name: '1 Reis', slug: '1+kings', testament: 'AT', category: 'Históricos', chapters: 22 },
  { name: '2 Reis', slug: '2+kings', testament: 'AT', category: 'Históricos', chapters: 25 },
  { name: '1 Crônicas', slug: '1+chronicles', testament: 'AT', category: 'Históricos', chapters: 29 },
  { name: '2 Crônicas', slug: '2+chronicles', testament: 'AT', category: 'Históricos', chapters: 36 },
  { name: 'Esdras', slug: 'ezra', testament: 'AT', category: 'Históricos', chapters: 10 },
  { name: 'Neemias', slug: 'nehemiah', testament: 'AT', category: 'Históricos', chapters: 13 },
  { name: 'Ester', slug: 'esther', testament: 'AT', category: 'Históricos', chapters: 10 },
  { name: 'Jó', slug: 'job', testament: 'AT', category: 'Poéticos', chapters: 42 },
  { name: 'Salmos', slug: 'psalms', testament: 'AT', category: 'Poéticos', chapters: 150 },
  { name: 'Provérbios', slug: 'proverbs', testament: 'AT', category: 'Poéticos', chapters: 31 },
  { name: 'Eclesiastes', slug: 'ecclesiastes', testament: 'AT', category: 'Poéticos', chapters: 12 },
  { name: 'Cantares', slug: 'song+of+solomon', testament: 'AT', category: 'Poéticos', chapters: 8 },
  { name: 'Isaías', slug: 'isaiah', testament: 'AT', category: 'Profetas Maiores', chapters: 66 },
  { name: 'Jeremias', slug: 'jeremiah', testament: 'AT', category: 'Profetas Maiores', chapters: 52 },
  { name: 'Lamentações', slug: 'lamentations', testament: 'AT', category: 'Profetas Maiores', chapters: 5 },
  { name: 'Ezequiel', slug: 'ezekiel', testament: 'AT', category: 'Profetas Maiores', chapters: 48 },
  { name: 'Daniel', slug: 'daniel', testament: 'AT', category: 'Profetas Maiores', chapters: 12 },
  { name: 'Oséias', slug: 'hosea', testament: 'AT', category: 'Profetas Menores', chapters: 14 },
  { name: 'Joel', slug: 'joel', testament: 'AT', category: 'Profetas Menores', chapters: 3 },
  { name: 'Amós', slug: 'amos', testament: 'AT', category: 'Profetas Menores', chapters: 9 },
  { name: 'Obadias', slug: 'obadiah', testament: 'AT', category: 'Profetas Menores', chapters: 1 },
  { name: 'Jonas', slug: 'jonah', testament: 'AT', category: 'Profetas Menores', chapters: 4 },
  { name: 'Miquéias', slug: 'micah', testament: 'AT', category: 'Profetas Menores', chapters: 7 },
  { name: 'Naum', slug: 'nahum', testament: 'AT', category: 'Profetas Menores', chapters: 3 },
  { name: 'Habacuque', slug: 'habakkuk', testament: 'AT', category: 'Profetas Menores', chapters: 3 },
  { name: 'Sofonias', slug: 'zephaniah', testament: 'AT', category: 'Profetas Menores', chapters: 3 },
  { name: 'Ageu', slug: 'haggai', testament: 'AT', category: 'Profetas Menores', chapters: 2 },
  { name: 'Zacarias', slug: 'zechariah', testament: 'AT', category: 'Profetas Menores', chapters: 14 },
  { name: 'Malaquias', slug: 'malachi', testament: 'AT', category: 'Profetas Menores', chapters: 4 },

  // Novo Testamento (27 livros)
  { name: 'Mateus', slug: 'matthew', testament: 'NT', category: 'Evangelhos', chapters: 28 },
  { name: 'Marcos', slug: 'mark', testament: 'NT', category: 'Evangelhos', chapters: 16 },
  { name: 'Lucas', slug: 'lucas', testament: 'NT', category: 'Evangelhos', chapters: 24 },
  { name: 'João', slug: 'john', testament: 'NT', category: 'Evangelhos', chapters: 21 },
  { name: 'Atos', slug: 'acts', testament: 'NT', category: 'Histórico', chapters: 28 },
  { name: 'Romanos', slug: 'romans', testament: 'NT', category: 'Cartas Paulinas', chapters: 16 },
  { name: '1 Coríntios', slug: '1+corinthians', testament: 'NT', category: 'Cartas Paulinas', chapters: 16 },
  { name: '2 Coríntios', slug: '2+corinthians', testament: 'NT', category: 'Cartas Paulinas', chapters: 13 },
  { name: 'Gálatas', slug: 'galatians', testament: 'NT', category: 'Cartas Paulinas', chapters: 6 },
  { name: 'Efésios', slug: 'ephesians', testament: 'NT', category: 'Cartas Paulinas', chapters: 6 },
  { name: 'Filipenses', slug: 'philippians', testament: 'NT', category: 'Cartas Paulinas', chapters: 4 },
  { name: 'Colossenses', slug: 'colossians', testament: 'NT', category: 'Cartas Paulinas', chapters: 4 },
  { name: '1 Tessalonicenses', slug: '1+thessalonians', testament: 'NT', category: 'Cartas Paulinas', chapters: 5 },
  { name: '2 Tessalonicenses', slug: '2+thessalonians', testament: 'NT', category: 'Cartas Paulinas', chapters: 3 },
  { name: '1 Timóteo', slug: '1+timothy', testament: 'NT', category: 'Cartas Paulinas', chapters: 6 },
  { name: '2 Timóteo', slug: '2+timothy', testament: 'NT', category: 'Cartas Paulinas', chapters: 4 },
  { name: 'Tito', slug: 'titus', testament: 'NT', category: 'Cartas Paulinas', chapters: 3 },
  { name: 'Filemom', slug: 'philemon', testament: 'NT', category: 'Cartas Paulinas', chapters: 1 },
  { name: 'Hebreus', slug: 'hebrews', testament: 'NT', category: 'Cartas Gerais', chapters: 13 },
  { name: 'Tiago', slug: 'james', testament: 'NT', category: 'Cartas Gerais', chapters: 5 },
  { name: '1 Pedro', slug: '1+peter', testament: 'NT', category: 'Cartas Gerais', chapters: 5 },
  { name: '2 Pedro', slug: '2+peter', testament: 'NT', category: 'Cartas Gerais', chapters: 3 },
  { name: '1 João', slug: '1+john', testament: 'NT', category: 'Cartas Gerais', chapters: 5 },
  { name: '2 João', slug: '2+john', testament: 'NT', category: 'Cartas Gerais', chapters: 1 },
  { name: '3 João', slug: '3+john', testament: 'NT', category: 'Cartas Gerais', chapters: 1 },
  { name: 'Judas', slug: 'jude', testament: 'NT', category: 'Cartas Gerais', chapters: 1 },
  { name: 'Apocalipse', slug: 'revelation', testament: 'NT', category: 'Revelação', chapters: 22 },
];
